import { ICreature, ICreatureStats } from "@/types";

export const creatures: { [key: string]: ICreature } = {
  ankylosaurus: {
    XPk: 6,
    FitsThrough: ["dinosaurGateway", "behemothGateway", "giantHatchframe"],
    CanDamage: ["thatchWall", "woodenWall"],
    AffectedBy: ["netProjectile", "largeBearTrap"],
    CarryableByFlyers: [
      "argentavis",
      "quetzal",
      "crystalWyvern",
      "rhyniognatha",
      "wyvern",
    ],
    CarryableByLand: ["karkinos", "tusoteuthis", "procoptodon"],
    foodBase: 0.003156,
    foodMult: 176.0315,
    tiba: 0.2, // TameIneffectivenessByAffinity
    needToTame: 3000,
    needToTamePerLevel: 150,
    link: "ankylosaurus",
    name: "Ankylosaurus",
    image: "/creatures/ankylosaurus.webp",
    tamingFood: ["Regular Kibble", "Crops", "Mejoberry", "Berries"],
    stats: {
      h: { b: 700, w: 140, t: 5.4 },
      s: { b: 175, w: 17.5, t: 10 },
      o: { b: 150, w: 15, t: 10 },
      f: { b: 3000, w: 300, t: 10 },
      w: { b: 250, w: 5, t: 4 },
      d: { b: 100, w: 5, t: 2, a: [{ b: 50 }] },
      m: {
        b: 100,
        w: null,
        t: 2.5,
        a: { w: { b: 120, sw: 264, st: 264 }, s: { b: 300 } },
      },
      t: { b: 420, w: 25.2, t: null },
    },
  },

  argentavis: {
    XPk: 7,
    FitsThrough: ["dinosaurGateway", "behemothGateway", "giantHatchframe"],
    CanDamage: ["thatchWall", "woodenWall"],
    AffectedBy: ["lasso", "netProjectile", "chainBola", "largeBearTrap"],
    CarryableByFlyers: [],
    CarryableByLand: ["megalosaurus", "procoptodon"],
    foodBase: 0.001852,
    foodMult: 199.983994,
    tiba: 1.875,
    needToTame: 2000,
    needToTamePerLevel: 100,
    link: "argentavis",
    name: "Argentavis",
    image: "/creatures/argentavis.webp",
    tamingFood: [
      "Superior Kibble|85",
      "Raw Mutton",
      "Raw Prime Meat",
      "Cooked Lamb Chop",
      "Cooked Prime Meat",
      "Raw Prime Fish Meat",
      "Raw Meat",
      "Cooked Prime Fish Meat",
      "Cooked Meat",
      "Raw Fish Meat",
      "Cooked Fish Meat",
    ],
    stats: {
      h: { b: 365, w: 73, t: 6.75 },
      s: { b: 400, w: 20, t: 7.5 },
      o: { b: 150, w: 15, t: 10 },
      f: { b: 2000, w: 200, t: 10 },
      w: { b: 400, w: 8, t: 5.5 },
      d: { b: 100, w: 5, t: 2.55, a: [{ b: 25 }] },
      m: {
        b: 100,
        w: null,
        t: 0,
        a: { w: { b: 260 }, f: { b: 600, sw: 727.5, st: 1350 } },
      },
      t: { b: 600, w: 36, t: null },
    },
  },

  managarmr: {
    XPk: 36,
    FitsThrough: ["behemothGateway", "giantHatchframe"],
    CanDamage: ["thatchWall", "woodenWall", "adobeWall", "stoneWall"],
    AffectedBy: [
      "netProjectile",
      "chainBola",
      "plantSpeciesYTrap",
      "largeBearTrap",
    ],
    CarryableByFlyers: [],
    CarryableByLand: [],
    foodBase: 0.001543,
    foodMult: 243.1,
    tiba: 1.875,
    needToTame: 2000,
    needToTamePerLevel: 100,
    link: "managarmr",
    name: "Managarmr",
    image: "/creatures/managarmr.webp",
    tamingFood: [
      "Exceptional Kibble|85",
      "Raw Mutton",
      "Raw Prime Meat",
      "Cooked Lamb Chop",
      "Cooked Prime Meat",
      "Raw Prime Fish Meat",
      "Raw Meat",
      "Cooked Prime Fish Meat",
      "Cooked Meat",
      "Raw Fish Meat",
      "Cooked Fish Meat",
    ],
    stats: {
      h: { b: 825, w: 165, t: 5.4 },
      s: { b: 300, w: 30, t: 10 },
      o: { b: 150, w: 15, t: 10 },
      f: { b: 2000, w: 200, t: 10 },
      w: { b: 300, w: 6, t: 4 },
      d: { b: 100, w: 5, t: 2, a: [{ b: 35 }, { b: 35 }] },
      m: { b: 100, w: null, t: 4.91 },
      t: { b: 800, w: 48, t: null },
    },
  },

  giganotosaurus: {
    name: "Giganotosaurus",
    link: "giganotosaurus",
    image: "/creatures/giganotosaurus.webp",
    XPk: 200,
    tiba: 1.25,
    needToTame: 5000,
    needToTamePerLevel: 160,
    foodBase: 0.002314,
    foodMult: 160.056335,
    CarryableByFlyers: [],
    CarryableByLand: [],
    FitsThrough: ["behemothGateway"],
    CanDamage: ["thatchWall", "woodenWall", "adobeWall", "stoneWall"],
    AffectedBy: ["largeBearTrap"],
    tamingFood: [
      "Exceptional Kibble|85",
      "Raw Mutton",
      "Raw Prime Meat",
      "Cooked Lamb Chop",
      "Cooked Prime Meat",
      "Raw Prime Fish Meat",
      "Raw Meat",
      "Cooked Prime Fish Meat",
      "Cooked Meat",
      "Raw Fish Meat",
      "Cooked Fish Meat",
    ],
    stats: {
      h: { b: 80000, w: 40, t: 0.04 },
      s: { b: 400, w: 0.2, t: 1 },
      o: { b: 150, w: 0.375, t: 2.5 },
      f: { b: 4000, w: 10, t: 2.5 },
      w: { b: 700, w: 7, t: 1 },
      d: { b: 100, w: 5, t: 0.85, a: [{ b: 500 }] },
      m: { b: 100, w: null, t: 0.31 },
      t: { b: 10000, w: 600, t: null },
    },
  },

  pteranodon: {
    name: "Pteranodon",
    link: "pteranodon",
    image: "/creatures/pteranodon.webp",
    XPk: 3,
    tiba: 3.125,
    needToTame: 1200,
    needToTamePerLevel: 60,
    foodBase: 0.001543,
    foodMult: 216.029373,
    CarryableByFlyers: [],
    CarryableByLand: ["megalosaurus", "karkinos", "procoptodon"],
    FitsThrough: [
      "doubleDoor",
      "dinosaurGateway",
      "behemothGateway",
      "giantHatchframe",
    ],
    CanDamage: ["thatchWall", "woodenWall"],
    AffectedBy: [
      "lasso",
      "bola",
      "netProjectile",
      "plantSpeciesYTrap",
      "bearTrap",
      "largeBearTrap",
    ],
    tamingFood: [
      "Regular Kibble",
      "Raw Mutton",
      "Raw Prime Meat",
      "Cooked Lamb Chop",
      "Cooked Prime Meat",
      "Raw Prime Fish Meat",
      "Raw Meat",
      "Cooked Prime Fish Meat",
      "Cooked Meat",
      "Raw Fish Meat",
      "Cooked Fish Meat",
    ],
    stats: {
      h: { b: 210, w: 42, t: 3 },
      s: { b: 150, w: 7.5, t: 4 },
      o: { b: 150, w: 15, t: 10 },
      f: { b: 1200, w: 120, t: 10 },
      w: { b: 120, w: 2.4, t: 3 },
      d: { b: 100, w: 5, t: 1.275, a: [{ b: 15 }] },
      m: { b: 100, w: null, t: 0 },
      t: { b: 120, w: 7.2, t: null },
    },
  },

  woollyrhino: {
    name: "Woolly Rhino",
    link: "woollyrhino",
    image: "/creatures/woollyrhino.webp",
    XPk: 4,
    tiba: 1.25,
    needToTame: 3450,
    needToTamePerLevel: 125,
    foodBase: 0.003156,
    foodMult: 150.0,
    CarryableByFlyers: ["quetzal", "rhyniognatha"],
    CarryableByLand: ["tusoteuthis", "procoptodon"],
    FitsThrough: ["dinosaurGateway", "behemothGateway"],
    CanDamage: ["thatchWall", "woodenWall"],
    AffectedBy: [
      "netProjectile",
      "chainBola",
      "plantSpeciesYTrap",
      "largeBearTrap",
    ],
    tamingFood: [
      "Superior Kibble|85",
      "Crops",
      "Mejoberry",
      "Berries",
    ],
    stats: {
      h: { b: 500, w: 100, t: 5.4 },
      s: { b: 120, w: 12, t: 10 },
      o: { b: 100, w: 10, t: 10 },
      f: { b: 3000, w: 300, t: 10 },
      w: { b: 750, w: 15, t: 2.5 },
      d: { b: 100, w: 5, t: 1.7, a: [{ b: 50 }] },
      m: { b: 100, w: null, t: 6 },
      t: { b: 600, w: 36, t: null },
    },
  },
};

export const creaturesList: ICreature[] = Object.values(creatures);

export const carryableBy: {
  Flyers: { [key: string]: string };
  Land: { [key: string]: string };
} = {
  Flyers: {
    pteranodon: "Pteranodon",
    tropeognathus: "Tropeognathus",
    tapejara: "Tapejara",
    griffin: "Griffin",
    desmodus: "Desmodus",
    argentavis: "Argentavis",
    crystalWyvern: "Crystal Wyvern",
    wyvern: "Wyvern",
    quetzal: "Quetzal",
    rhyniognatha: "Rhyniognatha",
  },
  Land: {
    human: "Human",
    megalosaurus: "Megalosaurus",
    karkinos: "Karkinos",
    tusoteuthis: "Tusoteuthis",
    procoptodon: "Procoptodon",
    kaprosuchus: "Kaprosuchus",
    gigantopithecus: "Gigantopithecus",
  },
};

export const AffectedBy: { [key: string]: string } = {
  lasso: "Lasso",
  bola: "Bola",
  netProjectile: "Net Projectile",
  chainBola: "Chain Bola",
  plantSpeciesYTrap: "Plant Species Y Trap",
  bearTrap: "Bear Trap",
  largeBearTrap: "Large Bear Trap",
};

export const CanDamage: { [key: string]: string } = {
  thatchWall: "Thatch",
  woodenWall: "Wood",
  adobeWall: "Adobe",
  stoneWall: "Stone",
  metalWall: "Metal",
  tekWall: "Tek",
};

export const FitsThrough: { [key: string]: string } = {
  doorframe: "Doorframe",
  doubleDoor: "Double Door",
  dinosaurGateway: "Dinosaur Gateway",
  behemothGateway: "Behemoth Gateway",
  hatchframe: "Hatchframe",
  giantHatchframe: "Giant Hatchframe",
};

export const carryingFlyersList: string[] = [
  "pteranodon",
  "tropeognathus",
  "tapejara",
  "griffin",
  "desmodus",
  "argentavis",
  "crystalWyvern",
  "wyvern",
  "quetzal",
  "rhyniognatha",
];

export const carryingOtherList: string[] = [
  "human",
  "megalosaurus",
  "karkinos",
  "tusoteuthis",
  "procoptodon",
  "kaprosuchus",
  "gigantopithecus",
];
export const canDamageStructuresList: string[] = [
  "thatchWall",
  "woodenWall",
  "adobeWall",
  "stoneWall",
  "metalWall",
  "tekWall",
];
export const affectedList: string[] = [
  "lasso",
  "bola",
  "netProjectile",
  "chainBola",
  "plantSpeciesYTrap",
  "bearTrap",
  "largeBearTrap",
];
export const fitsThroughList: string[] = [
  "doorframe",
  "doubleDoor",
  "dinosaurGateway",
  "behemothGateway",
  "hatchframe",
  "giantHatchframe",
];
export const statsAllList: (keyof ICreatureStats)[] = ["h", "s", "o", "f", "w", "d", "m", "t"];
